import type { SkillStoreState, Skill } from "@/types";

export interface SkillFile {
  path: string;
  content: string;
}

function toSlug(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}

function generateSkillFiles(skill: Skill): SkillFile[] {
  const slug = toSlug(skill.name);
  const frontmatter = `---\nname: ${skill.name}\ndescription: ${skill.description}\n---`;
  const files: SkillFile[] = [
    {
      path: `skills/${slug}/SKILL.md`,
      content: `${frontmatter}\n\n${skill.skillMd}`,
    },
  ];

  for (const script of skill.scripts) {
    const filename = script.filename.startsWith("scripts/")
      ? script.filename
      : `scripts/${script.filename}`;
    files.push({
      path: `skills/${slug}/${filename}`,
      content: script.content,
    });
  }

  return files;
}

function generateReadme(state: SkillStoreState): SkillFile {
  const lines: string[] = [
    `# ${state.skillName || "My Skills"}`,
    "",
    `OpenClaw skills generated by LabForge.`,
    "",
  ];

  if (state.skills.length > 0) {
    lines.push("## Skills", "");
    for (const s of state.skills) {
      lines.push(`- **${s.name}**: ${s.description} (${s.scripts.length} scripts)`);
    }
    lines.push("");
  }

  return { path: "README.md", content: lines.join("\n") };
}

function generateChangelog(state: SkillStoreState): SkillFile | null {
  if (!state.changelog || state.changelog.length === 0) return null;

  const lines: string[] = ["# Changelog", ""];
  for (const entry of state.changelog) {
    const date = new Date(entry.timestamp).toISOString().split("T")[0];
    lines.push(`## ${entry.version} - ${date}`, "");
    for (const change of entry.changes) {
      lines.push(`- ${change}`);
    }
    lines.push("");
  }

  return { path: "CHANGELOG.md", content: lines.join("\n") };
}

export function generateSkillStructure(state: SkillStoreState): SkillFile[] {
  const files: SkillFile[] = [];

  for (const skill of state.skills) {
    files.push(...generateSkillFiles(skill));
  }

  files.push(generateReadme(state));

  const changelog = generateChangelog(state);
  if (changelog) files.push(changelog);

  return files;
}
